/*
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * 
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 * FiscalPrinterApplet.java
 *
 * Created on 2011-10-09, 16:46:02
 */
package name.prokop.bart.fps.applet;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import name.prokop.bart.fps.FiscalPrinter;
import name.prokop.bart.fps.datamodel.Slip;
import name.prokop.bart.fps.util.PostClient;
import name.prokop.bart.fps.util.URLGrabber;
import org.json.JSONObject;

/**
 *
 * @author bart
 */
public class FiscalPrinterApplet extends javax.swing.JApplet {

    private URL documentBase = null;
    private String serialPort = "COM1";
    private Slip slipToPrint = Slip.getOneCentSlip();
    private FiscalPrinter.Type fiscalPrinterType = FiscalPrinter.Type.BogusFiscalPrinter;
    private String resultURL = "http://natanedwin.appspot.com/stats";

    /**
     * Initializes the applet FiscalPrinterApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiscalPrinterApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    try {
                        preinit();
                        initComponents();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            });
        } catch (InterruptedException | InvocationTargetException ex) {
            ex.printStackTrace(System.err);
        }
    }

    private void preinit() {
        try {
            documentBase = this.getDocumentBase();
        } catch (Exception e) {
        }
        System.out.println("Document base: " + documentBase);

        try {
            String slipURL = getParameter("SlipURL");
            System.out.println("SlipURL: " + slipURL);
            String json = URLGrabber.getDocumentAsString(slipURL);
            slipToPrint = new Slip(new JSONObject(json));
            System.out.println("Odczytany paragon:\n" + slipToPrint);
        } catch (Exception e) {
            System.err.println("Nie mogę odczytać SlipURL\n" + e.getMessage());
        }

        serialPort = getParameter("SerialPort");
        System.out.println("Port szeregowy: " + serialPort);

        try {
            fiscalPrinterType = FiscalPrinter.Type.valueOf(getParameter("FiscalPrinterType"));
        } catch (Exception e) {
        }
        System.out.println("Typ drukarki fiskalnej: " + fiscalPrinterType);

        resultURL = getParameter("ResultURL");
        System.out.println("Zwrotny POST: " + resultURL);
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Drukuj paragon.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Map<String, String> resultMap = new HashMap<>();
    try {
        FiscalPrinter fiscalPrinter = fiscalPrinterType.getFiscalPrinter(serialPort);
        fiscalPrinter.print(slipToPrint);
        jButton1.setEnabled(false);

        final Map<String, String> statMap = new HashMap<>();
        statMap.put("stat", "STAT_0001");
        statMap.put("reference", slipToPrint.getReference());
        statMap.put("documentBase", documentBase.toString());
        statMap.put("license", "e-kierowca");
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    PostClient.postClient("http://natanedwin.appspot.com/stats", statMap);
                } catch (IOException ioe) {
                }
            }
        }).start();

        resultMap.put("slipReference", slipToPrint.getReference());
        resultMap.put("result", "OK");
        jButton1.setText("Wydrukowano");
    } catch (Exception e) {
        resultMap.put("result", "ERROR");
        resultMap.put("exception", e.getMessage());
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    try {
        String result = PostClient.postClient(resultURL, resultMap);
        System.out.println("Wynik wywołania zwrotnego POST:\n" + result);
    } catch (Exception e) {
    }
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        javax.swing.JFrame app = new javax.swing.JFrame("Applet Container");
        app.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        app.setSize(800, 480);

        FiscalPrinterApplet applet = new FiscalPrinterApplet() {
            // When the local applet version is instantiated
            // we override getParameter and feed it the values we want.
            // This, of course, can also be done be extending the applet
            @Override
            public String getParameter(String name) {
                if (name.equalsIgnoreCase("serverBase")) {
                    return "http://e-dziecko.appspot.com";
                    //return "http://127.0.0.1:8888";
                }
                if (name.equalsIgnoreCase("przedszkoleKeyId")) {
                    // return "1"; // przedszkole Mrowla
                    // return "20001"; // przedszkole Trzciana
                    // return "27146"; // przedszkole Świlcza
                    return "28001"; // TT Soft - testowo
                    // return "29001"; // przedszkole Bratkowice
                }
                if (name.equalsIgnoreCase("SlipURL")) {
                    return "file:///bart/hobby/Slip.json";
                }
                return null;
            }
        };
        // sure to make the applet do its thing
        applet.init();
        app.setLayout(new java.awt.BorderLayout());
        // include it as a component.  local testing can now start
        app.getContentPane().add(applet, java.awt.BorderLayout.CENTER);
        app.setVisible(true);
    }
}
