/******************************************************************************/
/****        Generated by IBExpert 2006.12.13 12/29/2007 9:56:20 AM        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN_1250;

CREATE DATABASE 'D:\Bartek\Firebird\fdbs\EBasen.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN_1250;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_SLIPLINES_ID;
SET GENERATOR GEN_SLIPLINES_ID TO 54;

CREATE GENERATOR GEN_SLIPPAYMENTS_ID;
SET GENERATOR GEN_SLIPPAYMENTS_ID TO 12;

CREATE GENERATOR GEN_SLIPS_ID;
SET GENERATOR GEN_SLIPS_ID TO 4;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE SLIPLINES (
    ID         INTEGER NOT NULL,
    FKID_SLIP  INTEGER NOT NULL,
    NAME       CHAR(40) CHARACTER SET WIN1250 NOT NULL,
    AMOUNT     DOUBLE PRECISION NOT NULL,
    PRICE      DOUBLE PRECISION NOT NULL,
    TAXRATE    CHAR(5) CHARACTER SET WIN1250 NOT NULL
);


CREATE TABLE SLIPPAYMENTS (
    ID         INTEGER NOT NULL,
    FKID_SLIP  INTEGER NOT NULL,
    AMOUNT     DOUBLE PRECISION NOT NULL,
    NAME       VARCHAR(16) CHARACTER SET WIN1250,
    FORM       CHAR(10) CHARACTER SET WIN1250 NOT NULL
);


CREATE TABLE SLIPS (
    ID                 INTEGER NOT NULL,
    CASHBOXLOGO        CHAR(8) CHARACTER SET WIN1250 NOT NULL,
    EXTERNALREFERENCE  CHAR(16) CHARACTER SET WIN1250 NOT NULL,
    CASHIERNAME        VARCHAR(32) CHARACTER SET WIN1250 DEFAULT 'Operator' NOT NULL,
    CREATED_TS         TIMESTAMP DEFAULT 'now' NOT NULL,
    PRINTED_TS         TIMESTAMP
);




/******************************************************************************/
/****                          Unique Constraints                          ****/
/******************************************************************************/

ALTER TABLE SLIPS ADD CONSTRAINT UNQ1_SLIPS UNIQUE (EXTERNALREFERENCE);


/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE SLIPLINES ADD CONSTRAINT PK_SLIPLINES PRIMARY KEY (ID);
ALTER TABLE SLIPPAYMENTS ADD CONSTRAINT PK_SLIPPAYMENTS PRIMARY KEY (ID);
ALTER TABLE SLIPS ADD CONSTRAINT PK_SLIPS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE SLIPLINES ADD CONSTRAINT FK_SLIPLINES FOREIGN KEY (FKID_SLIP) REFERENCES SLIPS (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SLIPPAYMENTS ADD CONSTRAINT FK_SLIPPAYMENTS FOREIGN KEY (FKID_SLIP) REFERENCES SLIPS (ID) ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;


/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: SLIPLINES_BI0 */
CREATE TRIGGER SLIPLINES_BI0 FOR SLIPLINES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
  NEW.ID = GEN_ID(GEN_SLIPLINES_ID,1);
END
^


/* Trigger: SLIPPAYMENTS_BI0 */
CREATE TRIGGER SLIPPAYMENTS_BI0 FOR SLIPPAYMENTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
  NEW.ID = GEN_ID(GEN_SLIPPAYMENTS_ID,1);
END
^


/* Trigger: SLIPS_BI0 */
CREATE TRIGGER SLIPS_BI0 FOR SLIPS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
  NEW.ID = GEN_ID(GEN_SLIPS_ID,1);
END
^


SET TERM ; ^
